apiVersion: v1
kind: Service
metadata:
  name: react-application-service
spec:
  selector:
    app: reactapplication
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          # The port that the service will expose
      targetPort: 80     # The port on the pod where the app is running
      nodePort: 31110

